### ISSUE TITLE
missing json-jwt ruby gem

### ISSUE THREAD

**Issue by odigity** [jsonwebtoken/jsonwebtoken.github.io#100]
Your list of libraries is missing the second most popular jwt ruby gem:

https://github.com/nov/json-jwt

https://rubygems.org/search?utf8=%E2%9C%93&query=jwt

**Comment by nov** [comment]
Thanks @odigity ;-)

My gem supports all JOSE-family specs including JWT, JWS, JWE, JWK and JWK Set.
On the other hand, it doesn't care about verification of each JWT claims.
https://github.com/nov/json-jwt/wiki

It would be great if my gem is listed on the list.

**Comment by franklinyu** [comment]
This can be closed because #103 has been merged?
