### ISSUE TITLE
Serve jwt.io over HTTPS

### ISSUE THREAD

**Issue by brianreavis** [jsonwebtoken/jsonwebtoken.github.io#129]
I know this isn't the easiest fix given this is hosted on GitHub, but a site where people paste in potentially-secret tokens should *not* be served over HTTP. Granted, someone concerned about security should not be pasting into a web form in the first place... but let's be real, it happens. Thoughts?

Refs https://github.com/isaacs/github/issues/156

**Comment by woloski** [comment]
yep, we will move it. So many things in the backlog :) We need to buy the cert and move it to heroku probably.

**Comment by brianreavis** [comment]
Cool! Figured it was already on this list – just wanted to double check

**Comment by woloski** [comment]
Done! https://jwt.io
