### ISSUE TITLE
Libraries list does not show JWTDecode.swift

### ISSUE THREAD

**Issue by bradfol** [jsonwebtoken/jsonwebtoken.github.io#150]
The [JWT Swift library provided by Auth0](https://github.com/auth0/JWTDecode.swift) is not shown in the list of libraries.

**Comment by sebadoom** [comment]
Thank you for your report, however the JWTDecode library only decodes tokens and does not perform any validation. It does not allow you to create tokens either. IOW, it provides none of the functionality required to be submitted to JWT.io.
