### ISSUE TITLE
Verify Base64 standard encoding regarding padding

### ISSUE THREAD

**Issue by curtislinden** [jsonwebtoken/jsonwebtoken.github.io#153]
I'm noticing that some libraries (ruby JWT) are stripping padding '=' and  making a base64 string that is not decodable without re-appending '=' (which is what the ruby JWT does)

Of course I'm generating the JWT and using /verifying it in another language.

Does JWT officially have a position on the base64 standard and padding?

Would it be possible to make "conforms to standard base64 " part of the checkboxes that you have in the list of libraries.

Best Regards,

Curtis

**Comment by Spomky** [comment]
The base64 url safe encoded string without padding is described at https://tools.ietf.org/html/rfc7515#appendix-C

**Comment by curtislinden** [comment]
thank you so much Spomky!
