### ISSUE TITLE
Added Haxe Implementation

### ISSUE THREAD

**Issue by kevinresol** [jsonwebtoken/jsonwebtoken.github.io#157]
Hi there,

I have recently prepared the jwt implementation for the [Haxe](http://haxe.org/) language. It would be my pleasure to get it listed on the website. The repo can be found [here](https://github.com/kevinresol/jsonwebtoken).

Supported features at the moment:
Sign, verify, iss check, aud check, exp check, HS256

Thanks,
Kevin

**Comment by sebadoom** [comment]
We will take a look at this eventually. If you want this library added sooner you can create a PR with the necessary changes. Thanks!

**Comment by sebadoom** [comment]
In 1cb4eda
