### ISSUE TITLE
Add PostgreSQL JWT library?

### ISSUE THREAD

**Issue by michelp** [jsonwebtoken/jsonwebtoken.github.io#159]
Hey y'all, I'm working on a pure SQL postgresql implementation of JWT:

https://github.com/michelp/pgjwt

Right now I have sign, verify, and HS256/384/512.  Are you interested in me sending a PR to add the implementation to your page?

Thanks,

-Michel

**Comment by sebadoom** [comment]
I am not sure if this is still maintained and supported, but if so do send us a PR and we will include it. Thanks!

**Comment by sebadoom** [comment]
In c41015d
