### ISSUE TITLE
Node & js missing

### ISSUE THREAD

**Issue by PseudoCorps** [jsonwebtoken/jsonwebtoken.github.io#172]
Cant scroll maybe?

![screenshot_2016-06-16-20-52-53](https://cloud.githubusercontent.com/assets/2850172/16140370/a18839fe-3404-11e6-8b5a-5f421603a4b5.png)

**Comment by jotaen** [comment]
Some of the languages are missing in the dropdown list. There’s already a pull request for that: https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/171

**Comment by sebadoom** [comment]
TODO: check that PR: https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/186 did add all missing languages. If not, add them.

**Comment by sebadoom** [comment]
All languages are now available in the dropdown box. Thank you for your report.
