### ISSUE TITLE
Support Firefox in the Extension

### ISSUE THREAD

**Issue by callahad** [jsonwebtoken/jsonwebtoken.github.io#175]
Hi! I'm happy to take this, but which branch should I be working from? Looks like `chrome-extension`, but that's diverged a bit from `master` and currently has merge conflicts.

Suggestions?

**Comment by callahad** [comment]
FWIW, I'm currently in London, so I'll get to this early next week. With the exception of the keyboard shortcut and a panel sizing bug on our end, the add-on works in Firefox with zero modifications:

<img width="1180" alt="screen shot 2016-06-17 at 18 42 55" src="https://cloud.githubusercontent.com/assets/24193/16167506/7bdd912e-34bb-11e6-8fd9-09814e2fbd8c.png">

**Comment by sebadoom** [comment]
That's great. Please work off the chrome-extension branch. Master is currently dedicated to the main website and we haven't had time to actually merge both projects (the website and the extension).

**Comment by sebadoom** [comment]
@callahad Just a heads-up, development has moved to https://github.com/auth0/jwt-debugger-extension (master branch this time).

**Comment by callahad** [comment]
Awesome, I'll move over there. Spoiler: As soon as mozilla/addons-server#2726 hits production (Thursday?), this will be able to be closed with "just upload your unmodified CRX to addons.mozilla.org and you're done." ;)

**Comment by sebadoom** [comment]
@callahad Could the panel sizing issue be related to this bug? https://bugzilla.mozilla.org/show_bug.cgi?id=1215025

**Comment by sebadoom** [comment]
@callahad have you had time to investigate the panel sizing issue?

**Comment by sebadoom** [comment]
The Firefox extension is now live: https://addons.mozilla.org/en-US/firefox/addon/jwtio-debugger/

Thanks!
