### ISSUE TITLE
Fix HS256 example

### ISSUE THREAD

**Issue by 0x434d53** [jsonwebtoken/jsonwebtoken.github.io#178]
In security related areas we should always show good practices in examples:

As the secret in the HS256 example a secret based on the recommendations from RFC 4868 should be used: The length of the secret should at least the size of the block size of the hash function (64 bytes for SHA256). The used "secret" is way to short.

**Comment by sebadoom** [comment]
I think that right approach for this is to add a clear, visual warning near the "secret" input area for HS256. We will discuss this with the design team. Thanks.

**Comment by sebadoom** [comment]
Implemented in stage-6 branch (soon to be live). Thanks.
