### ISSUE TITLE
Process for adding a new lib?

### ISSUE THREAD

**Issue by ducks** [jsonwebtoken/jsonwebtoken.github.io#200]
Howdy all, 

sorry if I overlooked it but I cannot seem to find any docs on the steps to getting a new library added to the website.

I see a few other issues where people are asking to be added so I may not be the only one.

Thanks!

**Comment by rjgoldsborough** [comment]
bump?

**Comment by lolgear** [comment]
@rjgoldsborough I just copypaste existing lib and configure it to new lib.

1. fork repo
2. clone
3. look at /views/libraries/anylibrary.jade
4. copypaste any appropriate.
5. edit it.
6. make PR.

**Comment by sebadoom** [comment]
The process described by lolgear is correct. Send us a PR and we will review it. Thanks.
