### ISSUE TITLE
Debugger strange behavior 

### ISSUE THREAD

**Issue by olegdunkan** [jsonwebtoken/jsonwebtoken.github.io#216]
Try this token
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyRzMxR2w2MXN6eWRpY0V0S0VPVjRGZmo1SkxpREkxcyIsInNjb3BlcyI6eyJ1c2VycyI6eyJhY3Rpb25zIjpbImNyZWF0ZSJdfX0sImlhdCI6MTQ4MDc1NjY1NywianRpIjoiMWE4MGZjOGEzNGRiOTcyMWE2MmYzNTU2OWFhYWEwZDEifQ._VxfvWMtXN0YtA3S0kbNbVEp868kpS2akdEbmkEBw_g`

Secret is `oleg` and signature was verified - ok.
But the problem is when we type `oleg3` in the secret input, it will be also verified.
All values of the the kind `oleg+<any char>` will be verified.
Why? Is it a bug? Or I miss something?

**Comment by sebadoom** [comment]
What you describe only works if you enable "secret base64 encoded". What happens is that the base64 decoder is discarding stray characters when the length of the encoded data is wrong. We will make the base64 parser more strict. Thanks.

**Comment by sebadoom** [comment]
In ba880a2.
