### ISSUE TITLE
Grails JWT token implementation [Not an Issue]

### ISSUE THREAD

**Issue by vishnoor** [jsonwebtoken/jsonwebtoken.github.io#229]
I have used a JWT capable token generation plugin for Grails.
https://github.com/kaleidos/grails-security-stateless

Though it does not strictly follow JWT namings (such as sub, nbf etc) it can be modified for the same

**Comment by sebadoom** [comment]
We will take a look at this eventually. If you want this library added sooner you can create a PR with the necessary changes. Thanks.

**Comment by sebadoom** [comment]
In a00cd96
