### ISSUE TITLE
debugger: use embedded x5c to verify RS256 or allow to pass a PEM in via URL

### ISSUE THREAD

**Issue by martinpaljak** [jsonwebtoken/jsonwebtoken.github.io#232]
So that a link could be generated to decode AND verify a JWT with a single click

The JWT sub-format/profile is specified here: https://github.com/martinpaljak/x509-webauth/wiki/WebAuth but is fully conforming to JWS and OpenID ID Token

**Comment by martinpaljak** [comment]
Here's a full example: https://martinpaljak.net/jwt.txt

**Comment by martinpaljak** [comment]
I think that the "nicer way" would be to extract x5c if present in the JWT header and set it as the public key in PEM format? This will require some time to digest through the editor code, some hints would be nice.

**Comment by sebadoom** [comment]
In 7b20e49

The sample JWT contained in your `jwt.txt` is now validated after pasting.

**Comment by martinpaljak** [comment]
Cool. When this will be live in jwt.io?

**Comment by sebadoom** [comment]
There's a chance this will go live tomorrow, but I can't make any promises. Otherwise, it will probably go live some time next week.

**Comment by sebadoom** [comment]
@martinpaljak We have decided against deploying these changes until further improvements are in place. For the time being you can deploy your own version, or you can use this (unsupported) version I deployed during tests: 

https://jsonwebtokengithubio-hfdfmktrwf.now.sh/

If you find bugs in it, do report them as new issues, though. Thanks.
