### ISSUE TITLE
Show epoch timestamps in ISO8601 format

### ISSUE THREAD

**Issue by geekosphere-net** [jsonwebtoken/jsonwebtoken.github.io#233]
When looking at the debugger (which I love) it would be nice to have the ability to hover over the `exp` and `iat` to get the ISO8601 human readable format. See http://calebb.net/
![jwt](https://cloud.githubusercontent.com/assets/7292206/23567841/280958da-0026-11e7-94c2-5a01d783c545.png)

**Comment by sebadoom** [comment]
Related #266

**Comment by sebadoom** [comment]
In 43dc331, hovering over a claims with a date will display it in human readable form.

**Comment by geekosphere-net** [comment]
Thanks!!
