### ISSUE TITLE
https://jwt.io/ validator validates non-url-safe JWT without warning or error

### ISSUE THREAD

**Issue by mrdvt92** [jsonwebtoken/jsonwebtoken.github.io#237]
Can we update the validating logic on https://jwt.io/ to add an error/warning if the token has any non-url-safe characters in the token.  The token validator works perfectly using base64 encoding instead of the correct base64url encoding.  But, the characters [=/+] are not url safe so https://jwt.io/ should not validate those tokens as correct.

**Comment by mrdvt92** [comment]
duplicate of #160

**Comment by sebadoom** [comment]
In edd0abe
