### ISSUE TITLE
jwt.io does not function in China

### ISSUE THREAD

**Issue by ened** [jsonwebtoken/jsonwebtoken.github.io#248]
1. Loads Facebook SDK / connect - causes some console errors here
2. Loads jQuery via googleapis.com CDN, which is also blocked and prevents the entire site functionality from working

<img width="1091" alt="screen shot 2017-06-16 at 09 33 41" src="https://user-images.githubusercontent.com/269860/27208409-12f86c48-5278-11e7-9a5f-74b3037f054f.png">

**Comment by sebadoom** [comment]
Thanks for reporting this. We will investigate what options we have to fix this, though I wouldn't hold my hopes high.

**Comment by sebadoom** [comment]
As an alternative that may work, consider the jwt.io extension from the Chrome store.

**Comment by sebadoom** [comment]
Should be fixed in HEAD, please reopen if not. Thanks.
