### ISSUE TITLE
The JWT generator should accept arrays for the audience claim

### ISSUE THREAD

**Issue by rise-brb** [jsonwebtoken/jsonwebtoken.github.io#249]
According to RFC 7519:

>  In the general case, the "aud" value is an array of case-sensitive strings, each containing a StringOrURI value.  In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive String containing a StringOrURI value.

The setAudience()-method of the JwtBuilder only accepts a single String. Additionally, passing a collection of Strings should be supported, which are then formatted as a JSON array for the aud value.

**Comment by sebadoom** [comment]
Thank you for your report. We need to investigate, but this may be an issue with the library we are using for validation. We will eventually correct this. Thanks again.

**Comment by sebadoom** [comment]
Sorry, I misinterpreted what the bug report said. We do not provide any `setAudience` method for a `JwtBuilder` class at this site. If you are referring to some of the libraries developed by Auth0, please report this bug at the appropriate issue tracker for that library. Thanks.

**Comment by rise-brb** [comment]
I apologize for the confusion - this ticket was of course aimed at the java-jwt project at auth0. I must have missed the correct link on the page.
