### ISSUE TITLE
"alt": "none" validation bug on jwt.io

### ISSUE THREAD

**Issue by MrPrashantT** [jsonwebtoken/jsonwebtoken.github.io#251]
On https://jwt.io/, if I change "alg": "HS256" to "alg": "none", then the signature still passes validation. I can then change the body contents at will. 

This seems to be the very bug that the blog post in the warning on the same page warns about (https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/)

From: https://community.auth0.com/questions/4987/alt-none-validation-bug-on-jwtio

**Comment by sebadoom** [comment]
In c280e82e5e385908fd585a367a748593c3d21ef4 as hotfix. See #281.
