### ISSUE TITLE
Add ruby-jose

### ISSUE THREAD

**Issue by franklinyu** [jsonwebtoken/jsonwebtoken.github.io#252]
The [`jose`](http://www.rubydoc.info/gems/jose) gem did a good job at involving all the features of JOSE.

**Comment by sebadoom** [comment]
We will take a look at this eventually. If you want this library added sooner you can create a PR with the necessary changes. Thanks.

**Comment by sebadoom** [comment]
In 6ad19fa

Can you confirm whether the checkboxes are OK for this library? If not, please open a new issue.

Thanks.

**Comment by franklinyu** [comment]
LGTM! I'm not the author, but AFAIK that should be true.
