### ISSUE TITLE
Misleading introduction and video

### ISSUE THREAD

**Issue by mr6502** [jsonwebtoken/jsonwebtoken.github.io#261]
https://jwt.io/introduction/

>  that defines a compact and self-contained way for securely transmitting information between parties as a JSON object

https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/master/views/md/introduction.md

The author of this article and video confuses the cryptographic signing algorithm (securing only the authenticity and integrity of the message) with securing the payload data.

The video makes several references to this, not differentiating between MAC and data encryption. Unfortunately, the information is dangerous and misleading. There is even reference to using plain text HTTP with the implication that somehow the payload is protected. At one point in the video the author believe somehow base64encoding is encrypted (protecting the payload) itself.

+ JWT says very little about payload encryption (container format)
+ JWE is for data payload encryption (protecting the contents of the message)
+ JWS is about cryptographically signing (authenticity and integrity of the message)

**Comment by sebadoom** [comment]
You are entirely correct. We have removed the video with wrong content. Thank you for your report.

In c1c08f7
