### ISSUE TITLE
Local storage VS cookie

### ISSUE THREAD

**Issue by roelstorms** [jsonwebtoken/jsonwebtoken.github.io#262]
In the introduction: https://jwt.io/introduction/

"In authentication, when the user successfully logs in using their credentials, a JSON Web Token will be returned and must be saved locally (typically in local storage, but cookies can be also used), instead of the traditional approach of creating a session in the server and returning a cookie."

JWT tokens shouldn't be stored in local storage as they are then vulnerable to XSS attacks. They should be stored in cookie as described by stormpath here https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

**Comment by sebadoom** [comment]
Yes, local storage tokens are vulnerable to XSS attacks. OTOH, tokens stored as cookies are vulnerable to CSRF attacks. Furthermore, tokens stored as cookies without the http-only flag are vulnerable to both types of attacks. There are mitigation techniques for these attacks. It is up to the user to implement and use them. When the user needs to parse the contents of the token, it is usually stored in local storage. OTOH, when it is used as an opaque access token, it is better to keep it as an http-only cookie. Unfortunately, many services require the access token to be passed as an HTTP header. This precludes the use of the http-only flag and exposes tokens to XSS and CSRF attacks. This means that in practice, JWT are usually kept in local storage.

I'll see about rephrasing the sentence above to make this nuances clearer, thanks.

**Comment by sebadoom** [comment]
Fixed in c629b8f
