### ISSUE TITLE
Another Rust implementation

### ISSUE THREAD

**Issue by eliovir** [jsonwebtoken/jsonwebtoken.github.io#264]
The @Keats's crates https://github.com/Keats/jsonwebtoken supports the following algorithms: HS256, HS384, HS512, RS256, RS384, RS512.
> This library validates automatically the `iat`, `exp` and `nbf` claims if present. You can also validate the `sub`, `iss` and `aud` [..].

**Comment by sebadoom** [comment]
We will take a look at this eventually. If you want this library added sooner you can create a PR with the necessary changes.

**Comment by sebadoom** [comment]
Available in 090e00b.
