### ISSUE TITLE
Add Time Converter to Decoded JWT page

### ISSUE THREAD

**Issue by MNF** [jsonwebtoken/jsonwebtoken.github.io#266]
Currently decoded JWT page https://jwt.io/ shows time as  Unix epoch time like the following:
  "nbf": 1507432747,
  "exp": 1507433047,

It will be good to show also normal date/time format.
Or at least add a link to https://www.epochconverter.com/ to help users to do conversions themselves.

**Comment by sebadoom** [comment]
In 43dc331, hovering over a claims with a date will display it in human readable form.

**Comment by gaieges** [comment]
I was just looking to take advantage of this (handy!) feature, and saw that it wasn't rolled out yet .. is there an ETA on deployment to the jwt.io site?

Thanks for doing this!

**Comment by sebadoom** [comment]
We haven't set a date yet, but there's a chance it will go live by the end of this week. I can't make any promises, though.

**Comment by MNF** [comment]
Are you supporting tablets(e.g. iPad) and mobiles? They don’t have hover Event, but https://stackoverflow.com/questions/2851663/how-do-i-simulate-a-hover-with-a-touch-in-touch-enabled-browsers

**Comment by sebadoom** [comment]
@MNF Not yet, please add this as a new issue and we will take a look.

@gaieges We have decided against deploying these changes until further improvements are in place. For the time being you can deploy your own version, or you can use this (unsupported) version I deployed during tests: 

https://jsonwebtokengithubio-hfdfmktrwf.now.sh/

If you find bugs in it, do report them as new issues, though. Thanks.
