### ISSUE TITLE
C++ Implementation

### ISSUE THREAD

**Issue by Thalhammer** [jsonwebtoken/jsonwebtoken.github.io#269]
https://github.com/Thalhammer/jwt-cpp
It is a header-only c++ jwt implementation depending only on OpenSSL for crypto.
It supports all 9 algorithms for both verify and sign.
exp, iat, nbf are always validated and aud, sub, iss, jti are validated if required by the user.

// Disclaimer:
I'm the developer and maintainer of this library.

**Comment by sebadoom** [comment]
We will take a look at this eventually. If you want this library added sooner you can create a PR with the necessary changes.

**Comment by sebadoom** [comment]
Blocked by #278.

**Comment by sebadoom** [comment]
Fixed by PR #287
