### ISSUE TITLE
Old/unmaintained library cleanup

### ISSUE THREAD

**Issue by sebadoom** [jsonwebtoken/jsonwebtoken.github.io#277]
We should check all the libraries and remove the ones that appear to be unmaintained and unused.

**Comment by sebadoom** [comment]
namshi/jose (php2.jade) is unmaintained and should be removed (see #194).

**Comment by sebadoom** [comment]
Removed namshi/jose (php2.jade) in 3a7c00d

**Comment by dimitarnestorov** [comment]
Why isn't https://github.com/auth0/node-jsonwebtoken a part of the list, has the most stars/downloads out of the listed ones.

After all you guys made both the library and the website. Since the numbers are an order of magnitude larger than the ones listed I believe you deserve your spot there.

**Comment by sebadoom** [comment]
@dimitarnestorov node-jsonwebtoken is listed as one of the libraries (see Node rather than JS). Or do you mean something else?

**Comment by dimitarnestorov** [comment]
It seems like I skipped right past it. Maybe moving them around to be closer to each other would improve visibility.
