### ISSUE TITLE
Support missing signing algorithms

### ISSUE THREAD

**Issue by sebadoom** [jsonwebtoken/jsonwebtoken.github.io#283]
PR #146 and issue #111 request more signing algorithms. The library we are using for validating and signing tokens does not support ES512. Switch to another library if possible and add support for ES512.

Edit: HS384 is not supported either.
Edit 2: all RSASSA-PSS algorithms fail too.

**Comment by sebadoom** [comment]
Partially implemented in a18cbd9. We need better support from the underlying libraries. Review this issue again after updating libraries to the latest versions.

**Comment by sebadoom** [comment]
Almost there: we now support all signing algorithms except ES512 and PS512. The underlying libraries do not support them.

**Comment by Spomky** [comment]
Do not forget the brand new `EdDSA` signature algorithm introduces by the [RFC8037](https://tools.ietf.org/html/rfc8037) ;)

**Comment by ChaosCoder** [comment]
Is there any chance to get ES512 working? What library are you using that does not support ES512? Maybe it got added since those 2 years?

**Comment by Sambego** [comment]
Hey @ChaosCoder we do support ES512 on jwt.io.

We're using [node-jose](https://github.com/cisco/node-jose) under the hood because it can do all of the validating and generating on the front-end.

**Comment by ChaosCoder** [comment]
Ah, what is the reason that the ES512 option is disabled? 
<img width="231" alt="Bildschirmfoto 2020-08-18 um 20 18 30" src="https://user-images.githubusercontent.com/1395240/90551154-37bf1a80-e191-11ea-85a3-be7fc1f95bab.png">

**Comment by Sambego** [comment]
Webkit does not support the ES512 algorithm, see
- https://diafygi.github.io/webcrypto-examples/ (Check the ECDSA row in Safari)
- https://webkit.org/blog/7790/update-on-web-cryptography/

When visiting jwt.io in a chromium based browser or Firefox, the ES512 option is enabled.
