### ISSUE TITLE
automatically try to validate RSA tokens

### ISSUE THREAD

**Issue by axos88** [jsonwebtoken/jsonwebtoken.github.io#294]
Try to infer the key location from the issuer. if ISS looks like a valid url, try {ISS}/.well-known/jwks.json to download the key.

**Comment by sebadoom** [comment]
Hi, this is already implemented in a development branch, you can check it out here: https://jwtio-pr-293.herokuapp.com/

It is also available in the extensions (Chrome/Firefox).

It will go live in jwt.io soon. Cheers!
