### ISSUE TITLE
Broken link to JWT Handbook

### ISSUE THREAD

**Issue by Thiago-Caramelo** [jsonwebtoken/jsonwebtoken.github.io#300]
Hi there.

I'm on https://jwt.io/introduction/ and can't download JWT Handbook. There's an error:
ipaddr: the address has neither IPv6 nor IPv4 format

**Comment by sebadoom** [comment]
Works here, can you provide more details? Is this the handbook link you are seeing?

https://auth0.com/e-books/jwt-handbook

**Comment by Thiago-Caramelo** [comment]
Never mind, it worked at home.
