### ISSUE TITLE
Allow selection of multiple tokens passed in the URL

### ISSUE THREAD

**Issue by sebadoom** [jsonwebtoken/jsonwebtoken.github.io#307]
Since a05835314f444345cff23792603894340c85ab31 and PR #305, it is possible to use `access_token`, `id_token`, `value`, and `token` as the URL query string key for passing a token to JWT.io. As described in PR #305 this appears to be a common use scenario with Auth0 that works by putting `https://jwt.io` as the callback URL in the application settings (for quick debugging). Since OpenID Connect allows for returning several tokens in the same callback URL, it would be convenient for JWT.io to offer a way to select which token to display in the editor. 

The ideal implementation would look at each query string key, get the value for each key, detect if it is a valid JWT, and then add it to some sort of UI element for selection. Invalid JWTs should not be considered or added as possible selections.

**Comment by panva** [comment]
> Invalid JWTs should not be considered or added as possible selections.

This is already in place for all the predefined parameter names, #305 already parses and has all valid JWTs available. It's just the UI and switching logic that I didn't do.

> URL query string

And fragment.
