### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by kjur** [jsonwebtoken/jsonwebtoken.github.io#313]
Hi, I'm a developer of jsrsasign.

You are violating jsrsasign's license and copyrights by publishing JWT debug tool which is concluded some part of my codes:
https://jwt.io/js/index.js

Here is jsrsasign's license. 
https://github.com/kjur/jsrsasign/blob/master/LICENSE.txt

**Comment by sebadoom** [comment]
@kjur Please confirm that the changes introduces in 91119dc16a7cc3a79f3c5897afbff12d559f10e8 fix this. Thanks.

**Comment by sebadoom** [comment]
@kjur Please check that the latest changes conform to your requirements. Thanks.

**Comment by kjur** [comment]
Hi,

Please read linence notice carefully.
"
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
"

This means license text is included in your software not by link.
Your Chrome extension shall include it.
The jwt.io site may be fine but it would be better to
put license in jwt.io site not in github.com site.

Thanks.

**Comment by sebadoom** [comment]
As of today, JWT.io and the JWT Debugger extensions no longer rely on jsrsasign.
