### ISSUE TITLE
Typo in debugger placeholder: "Enter the it"

### ISSUE THREAD

**Issue by curtisgibby** [jsonwebtoken/jsonwebtoken.github.io#320]
https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/f23e2a5b7c1760ad3058fe85cdb8333cd27ea95f/views/token-editor-common.pug#L38

```
Private Key. Enter the it in plain text...
```

Should be: 
```
Private Key. Enter it in plain text...
```

**Comment by sebadoom** [comment]
Fixed by PR #322. Thanks for your report.
