### ISSUE TITLE
JWT verifying is very unintuitive

### ISSUE THREAD

**Issue by Christilut** [jsonwebtoken/jsonwebtoken.github.io#341]
It took me a while and some frustration to figure out that you have to paste in the secret first and then the token in order to verify it.
If I paste a token and then a secret, it will update my token to match the secret. It doesn't say this anywhere, it just says 'Signature verified'. This is highly unintuitive.

Please take a look at how this works from a UX perspective and perhaps consider some minor changes.

**Comment by 0xbkt** [comment]
It really is. Specifically with HS*, even when entering random values as secret key, the script returns “Signature Verified”. It's just broken.

**Comment by Sambego** [comment]
Thanks for the feedback, I will take a look at improving this behavior.
