### ISSUE TITLE
Why jwt.io is not using jsonwebtoken ?

### ISSUE THREAD

**Issue by Gnafu** [jsonwebtoken/jsonwebtoken.github.io#342]
I was trying to get an example on how to validate a keycloak token via javascript.
The jwt.io site is actually capable of validating the signature by pasting the JSON object in the "Public key field" (it's an RSA256 token ) 
For example
{
  "kid":"thisisthe-key-id",
  "kty":"RSA",
  "alg":"RS256",
  "use":"sig",
  "n":"verylongrandomascicharacters",
  "e":"AQAB"
}
But I found no way to use the same information with the jsonwebtoken library.
So I just checked the jwy.io site source code an noticed the "jsonwebtoken" is not used, instead it uses node-jose and custom functions to do the validation.

Is jsonwebtoken not generic enough to be used for the jwt.io page?

**Comment by Sambego** [comment]
Using `node-jose` gives us a bit more flexibility, that's why we use it for jwt.io.
