### ISSUE TITLE
Add type of crypto library for jwt-implementations.

### ISSUE THREAD

**Issue by lolgear** [jsonwebtoken/jsonwebtoken.github.io#344]
Of course, there are a lot ( no ) crypto-libraries that provide generic actions like signing/providing keys/verifying/etc. 

It would be nice to know **Which** crypto-library ( or several ) do each implementation use.

I see that most of implementations use OpenSSL (I am wrong ?), but, Objective-C JWT uses zero of OpenSSL ( only internal Apple Security.framework ).

Further, it would be nice to see a list of dependencies of these jwt-implementations.

**Comment by Sambego** [comment]
Thanks for the suggestion. This is beyond the scope of jwt.io.
