### ISSUE TITLE
Indicate support for PS256, PS384 and PS512 on libraries

### ISSUE THREAD

**Issue by Thalhammer** [jsonwebtoken/jsonwebtoken.github.io#354]
Show indicators for RSA-PSS support of libraries, as is already done for all other signing types.

**Comment by Sambego** [comment]
Support for RSA-PSS has been added by #373.

I've gone trough all libraries and updated their support if indicated in their documentation.

I created a new issue to add the other data (#374). We have to make sure we show only relevant data without overwhelming users with data.
