### ISSUE TITLE
Add JWT.Net to the list of libraries

### ISSUE THREAD

**Issue by monsdar** [jsonwebtoken/jsonwebtoken.github.io#361]
I've recently reached out in the [forums](https://community.auth0.com/t/jwt-net-not-in-the-list/17047) and via the [JWT.Net bugtracker](https://github.com/jwt-dotnet/jwt/issues/178) about adding JWT.Net to the list of libraries on jwt.io.

There are some open questions from the maintainer of JWT.Net, but overall he provided a list of supported features. Would be cool if you could help out clearing the last few things up and then add the lib.

**Comment by Sambego** [comment]
Hey @monsdar you can create a pull-request adding the `JWT.net` library to this file: https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/master/views/website/libraries/0-.NET.json.

The JSON file contains an array of .NET libraries, to add a new one simply add the following object with the correct details:

```
{
  "minimumVersion": "1.0.0",
  "support": {
    "sign": true,
    "verify": true,
    "iss": true,
    "sub": true,
    "aud": true,
    "exp": true,
    "nbf": true,
    "iat": true,
    "jti": true,
    "hs256": true,
    "hs384": true,
    "hs512": true,
    "rs256": true,
    "rs384": true,
    "rs512": true,
    "es256": true,
    "es384": true,
    "es512": true
  },
  "authorUrl": "https://github.com/organisation",
  "authorName": "Your Name",
  "gitHubRepoPath": "organisation/project",
  "repoUrl": "https://github.com/organisation/project",
  "installCommandHtml": "..."
},
```

If you have any more questions, feel free to ping me here!
