### ISSUE TITLE
Validate prefixes before signature verification

### ISSUE THREAD

**Issue by bunyk** [jsonwebtoken/jsonwebtoken.github.io#364]
I pasted my JWT token and public key to appropriate fields on https://jwt.io/  and got "invalid signature" error. For some time I was trying to figure out where to get the correct public key, or what is wrong with the signature of my token, but today I tried to add "-----BEGIN PUBLIC KEY-----" and "-----END PUBLIC KEY----" lines into the edit field for public key, and got "signature verified". 

Could you somehow add error message like "BEGIN PUBLIC KEY is missing from public key text" or add required strings automatically?

**Comment by ravikumarvf** [comment]
I ended up with the same issue. It would be helpful to add that as comment to include them  or add an error message.
