### ISSUE TITLE
New PHP library

### ISSUE THREAD

**Issue by Spomky** [jsonwebtoken/jsonwebtoken.github.io#37]
Hi,

I created a new PHP library.
Even if this library has to be improved, it is quite stable now.

This is a very complete library and provides:
* [x] JWK support
* [x] JWKSet support,
* [x] JWS support including:
    * [x] all signature algorithms support
    * [x] Compact, Flattened or multiple signature serialisation representation support,
* [x] JWE support including
    * [x] all key encryption algorithms support
    * [x] all content encryption algorithms support
    * [x] compression support
    * [x] Compact, Flattened or multiple recipients serialisation representation support,

More information at [Spomky-Labs/jose](https://github.com/Spomky-Labs/jose).
The documentation is not complete.

It will be great if you can test it and send me feedbacks.

**Comment by csarrazi** [comment]
:+1:

Nice one! There is a conflict, in the PR!

**Comment by Spomky** [comment]
@csarrazi you are right, there is a conflict.
Maybe because of a lot of changes since I submitted my PR.
I will update it soon.

**Comment by pose** [comment]
Please do update to the latest update and I'll merge it. Thanks!

**Comment by Spomky** [comment]
Hi, 

As there are lot of changes, I prefer to close my PR and create a new one soon.
