### ISSUE TITLE
JWK, JWE, JOSE -- pull or fork?

### ISSUE THREAD

**Issue by bencmbrook** [jsonwebtoken/jsonwebtoken.github.io#378]
Do the maintainers expect to keep the scope of this project limited to JWT only? I understand Auth0 primarily uses JWT, so it makes sense.

To help drive adoption of the JOSE standards, it'd be great to have an index of modules which support encryption and reading JWKs and so on. Particularly lacking is the PKI, so having guides on reading/writing to a JWKS is important, as well as an index of modules that support them.

Should this be [jwt.io](https://jwt.io) or a new, separate website with different maintainers?

**Comment by Sambego** [comment]
Hey @bencmbrook, we are currently only focusing on JSON Web Tokens with jwt.io. We are however exploring the idea of another informational website about the JOSE standards and all things related.
