### ISSUE TITLE
Site jwt.io brings power workstation to the knees

### ISSUE THREAD

**Issue by mcd-php** [jsonwebtoken/jsonwebtoken.github.io#38]
I have so much CPU and RAM I can't even recall numbers, I know I can open as much as 4 resource-hog IDE's written in Java and feel no slightest glimpse of slowdown.

Then I open jwt.io, all GUI feels sluggish, and whatever browser I use to open, takes near all CPU as of `htop`.

Where's no version info in `index.html`, `wget jwt.io -O - | md5sum` = `54929852d61a4736925d199cb72e2bcc`.

Please fix, or do release comprehensive command line utilty to manipulate tokens.

P.S. OS is Ubuntu updated daily, browsers are latest Firefox and Chrome.

**Comment by pose** [comment]
Thanks for reporting @mcd-php. This has been fixed. Let me know if you are still experiencing issues.
