### ISSUE TITLE
jwerl and Guardian sign differently

### ISSUE THREAD

**Issue by cgrtrifork** [jsonwebtoken/jsonwebtoken.github.io#381]
After having trouble implementing an ES512 token generation/verification system, I think I found out Elixir's Guardian and Erlang's jwerl libraries treat signing and verifying differently. Using the same private keys, they generate a different signature for the same data.

**Comment by Sambego** [comment]
Hey @cgrtrifork, thanks for reporting this.

This website is only a list of libraries that can help when working with JWTs. You can report all bugs with the maintainers of those libraries.
