### ISSUE TITLE
Show definition or highlight spec claims

### ISSUE THREAD

**Issue by rolodato** [jsonwebtoken/jsonwebtoken.github.io#39]
It would be great if the definitions of the built-in claims of the spec (e.g. `jti`, `iat`, etc.) could be seen by hovering over the claim name. As a first step, it might be useful to highlight these claims in some way as to distinguish them from custom claims.

For a list of claims, see https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.

**Comment by pose** [comment]
For implementation details, see: http://codemirror.977696.n3.nabble.com/How-to-create-a-theme-that-uses-tooltips-td4025562.html

**Comment by sebadoom** [comment]
In d235692.
