### ISSUE TITLE
Signature Verification always passes

### ISSUE THREAD

**Issue by rmileskcl** [jsonwebtoken/jsonwebtoken.github.io#417]
When checking my JWT implementation I copied an encoded JWT into the "Encoded" field.

This showed "Invalid Signature" as expected.

I wanted to check that the token had been signed with the correct key so edited the "Verify Signature" field. As I was typing the key, the encoded token was regenerated resulting in "Signature Verified" appearing when I was not expecting it.

It appears that the encoded token is generated on the fly as the "Decoded" fields are edited. I think this makes sense for the "Header" and "Payload" fields but I'm not sure it makes sense for the "Verify Signature" fields

**Comment by lbalmaceda** [comment]
@rmileskcl yes. The current behavior is: as you type the new secret value, the token is re-generated and thus re-signed with that secret you are typing. The same happens when you change the header and payload boxes as you pointed out.
