### ISSUE TITLE
JWT Expired tokens always verify 

### ISSUE THREAD

**Issue by mirzaumersaleem** [jsonwebtoken/jsonwebtoken.github.io#421]
currently i am implementing json web tokens with passport, and i noticed that expired tokens also verify each time i made a request , my sample token : " Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkcml2ZXJJZCI6IjVkNjdhYTI5YWU4YjFjMzkzOTgwMjEzZSIsImlhdCI6MTU3MTAzODYwMSwibmJmIjoxNTcxMDM4NjAzLCJleHAiOjE1NzEwNDIyMDEwMjd9.lFfK5s4cbl6RM5r7JiKOomWiVytZIqVZp6aHerClDKQ"
my sample code to verify user is below  
> exports.user = function (req, res, next) {
  let errormessage = [{ message: "" }];
  let token =
    req.body.authorization  ||
    req.query.authorization ||
    req.headers["authorization"];
  if (token) {
    let temp = token.split(" ");
    token = temp[1];
    console.log(token , 'token');
    jwt.verify(token, secretKey, (err, decoded) => {
      console.log(err , decoded , 'err , decoded ');
      if (err) {
        errormessage[0].message = "You are not authorized to perform this operation";
        return res.status(400).json({
          success: false,
          message: errormessage
        });
      } else {
        req._user = decoded;
        next();
      }
    });
  } else {
    errormessage[0].message = "No token provided !";
    return res.status(400).json({
      success: false,
      errors: errormessage
    });
  }
};
jsonwebtokens version : 

> "jsonwebtoken": "^8.5.1"

**Comment by panva** [comment]
@mirzaumersaleem as you can see in the [parsed](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkcml2ZXJJZCI6IjVkNjdhYTI5YWU4YjFjMzkzOTgwMjEzZSIsImlhdCI6MTU3MTAzODYwMSwibmJmIjoxNTcxMDM4NjAzLCJleHAiOjE1NzEwNDIyMDEwMjd9.lFfK5s4cbl6RM5r7JiKOomWiVytZIqVZp6aHerClDKQ) JWT your `exp` value is in the year 51754.

The `exp` claim is defined as 

> A JSON numeric value representing the number of **seconds** from 1970-01-01T00:00:00Z UTC

You're likely passing milliseconds now, instead of seconds.

**Comment by panva** [comment]
Also, issues with the `jsonwebtoken` library belong to https://github.com/auth0/node-jsonwebtoken

**Comment by mirzaumersaleem** [comment]
> @mirzaumersaleem as you can see in the [parsed](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkcml2ZXJJZCI6IjVkNjdhYTI5YWU4YjFjMzkzOTgwMjEzZSIsImlhdCI6MTU3MTAzODYwMSwibmJmIjoxNTcxMDM4NjAzLCJleHAiOjE1NzEwNDIyMDEwMjd9.lFfK5s4cbl6RM5r7JiKOomWiVytZIqVZp6aHerClDKQ) JWT your `exp` value is in the year 51754.
> 
> The `exp` claim is defined as
> 
> > A JSON numeric value representing the number of **seconds** from 1970-01-01T00:00:00Z UTC
> 
> You're likely passing milliseconds now, instead of seconds.

![timestampoftoken](https://user-images.githubusercontent.com/16153073/66748934-eb84b900-eea1-11e9-99d5-ab2f3c15f7a8.PNG)

i have set my exp time correctly , check below code thanks   
  let 

> let d = new Date();
> calculatedExpiresIn = (((d.getTime()) + (60 * 60 * 1000)) - (d.getTime() - d.getMilliseconds()) / 1000);

**Comment by panva** [comment]
That, unfortunately, is incorrect.

**Comment by mirzaumersaleem** [comment]
@panva thanks for your quick reply , can you assist me on right path with example, so that it can be more help full for me and others

**Comment by panva** [comment]
Your timestamp should represent **seconds**, not milliseconds.

**Comment by mirzaumersaleem** [comment]
it works thanks champ :)
