### ISSUE TITLE
Fix encoding issues

### ISSUE THREAD

**Issue by rolodato** [jsonwebtoken/jsonwebtoken.github.io#43]
![image](https://cloud.githubusercontent.com/assets/829698/6198145/fe458cea-b3d2-11e4-8d04-ee743dcd93ea.png)

Most likely this is UTF-8 encoded. It's rendered correctly elsewhere :)

Related to #22

**Comment by pose** [comment]
@rolodato seems that it has been fixed. Please reopen if that's not the case!
