### ISSUE TITLE
landing page hash url not respected

### ISSUE THREAD

**Issue by nminchow** [jsonwebtoken/jsonwebtoken.github.io#432]
It appears that the intended behavior of [https://jwt.io/#libraries](https://jwt.io/#libraries) and [https://jwt.io/#debugger](https://jwt.io/#debugger) (as linked to by the introduction page) is that the relevant section will be scrolled to after navigation. This does not seem to functioning in firefox or chrome.

**Comment by carlos-menezes** [comment]
See: #447

**Comment by Sambego** [comment]
Thanks for the report, this is fixed by #447
