### ISSUE TITLE
Bigint modified after decoding

### ISSUE THREAD

**Issue by robertodecurnex** [jsonwebtoken/jsonwebtoken.github.io#450]
Hi guys, so seems like something between decoding the base64 and displaying the values on the right is making bigints change by small magnitudes. It is probably related with how you parse the number initially, loosing some precision, that translates into a different integer on the other side 

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJ3ZWJhcHAiLCJzdWIiOjEwMDAwMjM0ODExNzQyMTQ3MywiYXVkIjpbImFsbCJdLCJleHAiOjE1ODIyMTM2NTcsIm5iZiI6MTU4MTYwODg0NywiaWF0IjoxNTgxNjA4ODQ3LCJqdGkiOiI0YTNhNDVhZTUwZGNiYzkxMzkwNjJiMjMyYWVjZDQ2YyJ9.anYbiVdj5v-32RYwf48l-KJmsiK-q9QF0RqQ8rEbEYe03MCczVoBJx6gsKEeoy6wKaknKNrY4_xw7teWPlXyOA`

Note that sub in here is `100002348117421473`, but it gets displayed as `100002348117421470`.

I'll try to check the code if I'm able to make some room over the week .

**Comment by panva** [comment]
One of the very reasons `sub` is defined as a string value.

```sh
$ node -e 'console.log(Number.MAX_SAFE_INTEGER < 100002348117421473);'                                  
true
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by robertodecurnex** [comment]
Thank you guys. 

Closing as https://tools.ietf.org/html/rfc7519#section-4.1.2 states **sub** is case-sensitive **string**. 

```
4.1.2.  "sub" (Subject) Claim

   The "sub" (subject) claim identifies the principal that is the
   subject of the JWT.  The claims in a JWT are normally statements
   about the subject.  The subject value MUST either be scoped to be
   locally unique in the context of the issuer or be globally unique.
   The processing of this claim is generally application specific.  The
   "sub" value is a case-sensitive string containing a StringOrURI
   value.  Use of this claim is OPTIONAL.
```
