### ISSUE TITLE
Remove https://github.com/Spomky-Labs/jose from PHP libraries list

### ISSUE THREAD

**Issue by barell** [jsonwebtoken/jsonwebtoken.github.io#465]
Hi All,

https://github.com/Spomky-Labs/jose says it's no longer maintained in favour of https://github.com/web-token/jwt-framework. Can it be removed please?

**Comment by Spomky** [comment]
No problem to remove it.
I kept it because security fixed are still published.

**Comment by Sambego** [comment]
Thanks for the info @barell. As the library still gets security fixes, we'll keep in on the website, for now, just to keep the list as complete as possible.

**Comment by Spomky** [comment]
`spomky-labs/jose` is not maintained anymore.
I will create a PR to remove it.
