### ISSUE TITLE
No GDPR compliance

### ISSUE THREAD

**Issue by jnehlmeier** [jsonwebtoken/jsonwebtoken.github.io#467]
Currently jwt.io shows a small banner at the bottom containing the text

`
We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. We also share information about your use of our site with our social media, advertising and analytics partners.
`

However this is not enough to be GDPR compliant. You have to actively ask for consent to use any kind of cookies that track users. It is also not allowed to pre-check any consent checkboxes. The user have to actively give consent. 

So the current solution does not make the site GDPR compliant.

https://gdpr.eu/cookies/
https://www.cookiebot.com/en/gdpr-cookies/

**Comment by pxeger** [comment]
This is illegal and if this issue is not fixed imminently I will be forced to report the website to the Data Protection authority in the UK.
(to be honest, a website like this needs no cookies at all! Ideally you would just remove them.)
CC @FadyMak @mgonto @auth0

**Comment by Sambego** [comment]
Thanks for reporting this 💪 

I'll be looking into what we can do to be GDPR compliant and will post further updates in this thread.

**Comment by Sambego** [comment]
We're using a service (cookiepro.com) to show the cookie consent. We're working with them to get a full GDPR proof consent on this website asap.

**Comment by Sambego** [comment]
Update: Our (Auth0) legal department is reviewing the  proposed solution by cookiepro.com. We're hoping to be done with this and have a new and improved cookie-consent ready soon.

**Comment by Sambego** [comment]
It took a while, but as of now, we have a new and improved cookie consent that is GDPR compliant.
