### ISSUE TITLE
Extension stopped listing JWTs

### ISSUE THREAD

**Issue by mvilrokx** [jsonwebtoken/jsonwebtoken.github.io#489]
We've just noticed that this extension does not list the JWTs anymore in the dropdown list with the label "Open JWT from:". It just shows:

Web Storage
   No JWTs found
Cookies
   No JWTs found

We are on version 3.2.0 of the extension and Chrome Version 86.0.4240.111 (Official Build) (x86_64).

This worked fine in the previous version of the extension.

**Comment by christianklemp-imt** [comment]
I am also seeing this same issue. Would love to see it fixed soon since it's been a while with having to go find the token and copy & paste it into the extension.

Browser: Brave (Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (x86_64))
Extension Version: 3.2.0

**Comment by mvilrokx** [comment]
This issue is not `stale`.

**Comment by tstackhouse** [comment]
I'm seeing this in firefox as well, I set 2 jwts in cookies but they don't show up in the selector at all.  Is there some kind of naming convention or something that it preventing this? Or could it be because they are HTTP only?
