### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by LosD** [jsonwebtoken/jsonwebtoken.github.io#512]
You seem to have polluted jwt.io with the same scripts as you use for your main Auth0 site.

Is that really necessary? It's a site for examining JWTs and informing about them. There is no need for Twitter or Facebook or spam like that of any kind. Hence, there should be no need for any banner.

Making it all worse, you seem to disrespect saying no, setting tons of tracking cookies even before asking. It should not be necessary to point out that you are breaking the GDPR by doing that (and you are eroding any trust in a security sensitive site).

**Comment by Sambego** [comment]
Thanks for your feedback!

- Regarding the tracking. I'm looking into whether we need all these tracking services with our analytics team. 
- Regarding the cookie consent not working properly. I've taken this up with our Cookie Consent vendor, and they are looking into this. No tracking cookies should be set when choosing only to use necessary cookies.

I will get back here with an update when new info is available.

**Comment by LosD** [comment]
Thanks! :)

**Comment by LosD** [comment]
Just checked again. A bit better, but still pretty bad:
Cookies by clickfunnels.com and (apparently) unitary.io are set on jwt.io's own domain before accepting cookies. They are mentioned nowhere in the consent form.

**Comment by Sambego** [comment]
Thanks for the heads-up, I will look into why these are set without consent!

**Comment by LosD** [comment]
Correction: Cookies are apperently from Google Analytics and AdSense: _gcl_au, _gd_visitor, _gd_svisitor _gd_session (doesn't exactly make i better, though)

Still not sure about other: _hp2_ses_props.1279799279 and _hp2_id.1279799279

**Comment by LosD** [comment]
6suuid: 6Sense (some marketing tracker)

**Comment by LosD** [comment]
@Sambego Thanks

**Comment by johanadivare** [comment]
@LosD ticket can be closed than?

**Comment by LosD** [comment]
@johnadivare That depends if you stopped adding tracking cookies to jwt.io? It's untrustable until then (and illegal in EU if it still does it without consent) 

I've stopped using it in favor of jwt.ms, as that doesn't set any cookies, and doesn't send any data back to the servers. Which is a shame, as it is much less functional.

**Comment by LosD** [comment]
Took a look today, and seems to be fixed, only cookies are the consent cookies (even if you say yes, which of course make it a bit unnecessary, but MUCH better than the other way around)! 🎉 🥳
