### ISSUE TITLE
Debugger falsely rejects tokens with empty protected header as invalid

### ISSUE THREAD

**Issue by mrbax** [jsonwebtoken/jsonwebtoken.github.io#513]
```
>>> jwk = jwcrypto.jwk.JWK.generate( kty = 'oct' )
>>> jws = jwcrypto.jws.JWS( f'{{"exp": {int( time.time() )}}}' )
>>> jws.add_signature( jwk, alg = 'HS256' )
>>> jws.verify( jwk, alg = 'HS256' )
>>> print( jws.serialize( True ) )
.eyJleHAiOiAxNjEwMTgxMjQ1fQ.uiq38Mpw_lM5QaEuimB7Qq0k8Oypk4svDS-MU_ndYQI
```

![image](https://user-images.githubusercontent.com/13304143/104087210-c7f81c00-5266-11eb-8a5d-92836c9ab63a.png)

**Comment by panva** [comment]
A JWT (Compact Serialized JWS) must have a protected header because it is the only JOSE Header location available in that serialization and it must bear the "alg" header parameter.

**Comment by Spomky** [comment]
https://tools.ietf.org/html/rfc7515#section-4.1.1

**Comment by mrbax** [comment]
> A JWT (Compact Serialized JWS) must have a protected header because it is the only JOSE Header location available in said serialization and it must bear the "alg" header parameter which MUST always be present.

That is not correct; in fact the RFC specifically states:
> If the JWS Protected Header is not present (which can only happen when using the JWS JSON Serialization and no "protected" member is present), let this value be the empty string.

**Comment by mrbax** [comment]
> https://tools.ietf.org/html/rfc7515#section-4.1.1

States that the _alg_ header parameter must be present and must be understood and processed by implementations, but _not_ that it must be in the _protected_ header.

**Comment by panva** [comment]
@mrbax **there's no _unprotected_ header in Compact JWS Serialization**. Hence _protected_ must be present with the `alg` header parameter.

**Comment by mrbax** [comment]
> where's the `alg` header parameter in this token?

My argument is that it was in the unprotected header, which was discarded by compact serialization.

**Comment by panva** [comment]
> JWS Protected Header
>   JSON object that contains the Header Parameters that are integrity
>   protected by the JWS Signature digital signature or MAC operation.
>   **_For the JWS Compact Serialization, this comprises the entire JOSE
>   Header._**  For the JWS JSON Serialization, this is one component of
>   the JOSE Header.

**Comment by mrbax** [comment]
I agree that the protected header comprises the entire JOSE Header _in the JWS Compact Serialization_.  But the requirement for the _alg_ parameter applies to the object, not its serialized representation.

**Comment by panva** [comment]
Please see https://tools.ietf.org/html/rfc7515#section-5.2, particularly points 4 and 8

**Comment by mrbax** [comment]
> Please see https://tools.ietf.org/html/rfc7515#section-5.2, particularly points 4 and 8

I think point 8 is your strongest argument so far, but the question of an assumed value for _alg_ (restored during deserialization) remains open.

_However_, I found this definitive statement in section 10.7:

> Require that the "alg" Header Parameter be carried in the JWS Protected Header.  (This is always the case when using the JWS Compact Serialization…).

Thus the "alg" header parameter is explicitly required to be carried in the JWS protected header when using JWS Compact Serialization.

I do think that the RFC should make this point more clearly in 4.1.1 or 5.1.5, e.g. "The "alg" (algorithm) Header Parameter MUST be present in the _serialized_ JOSE Header".
