### ISSUE TITLE
Incorrect date parsing in tooltips on website

### ISSUE THREAD

**Issue by tevon456** [jsonwebtoken/jsonwebtoken.github.io#535]
The JWT parser on the page is providing the wrong date in the tooltip when you hover over the exp or iat.

**Comment by Sambego** [comment]
Are you sure your timestamps are in the correct format, as specified here: https://tools.ietf.org/html/rfc7519#section-2
Note it needs to be the number of **seconds** not **milliseconds** since 1970-01-01T00:00:00Z UTC.
> NumericDate
    A JSON numeric value representing the number of seconds from
    1970-01-01T00:00:00Z UTC until the specified UTC date/time,
    ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
    2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
    which each day is accounted for by exactly 86400 seconds, other
    than that non-integer values can be represented.  See RFC 3339
    [RFC3339] for details regarding date/times in general and UTC in
    particular.

**Comment by tevon456** [comment]
So it seems my timestamps were of due to some incorrect js my bad
