### ISSUE TITLE
Full JOSE implementation libraries for .NET and Golang

### ISSUE THREAD

**Issue by dvsekhvalnov** [jsonwebtoken/jsonwebtoken.github.io#54]
Hey guys, unsure if you list only high level JWT implementation on your site or just JOSE will work, but here is couple libraries with full alg suite.

https://github.com/dvsekhvalnov/jose2go
https://github.com/dvsekhvalnov/jose-jwt
https://github.com/dvsekhvalnov/jose-rt  (not full yet)

**Comment by pose** [comment]
Sure, we also accept JOSE implementations. @dvsekhvalnov would you mind creating a Pull Request with those libraries? Thanks in advance!

**Comment by dvsekhvalnov** [comment]
Here you go:
https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/93

**Comment by pose** [comment]
Merged, thanks!
