### ISSUE TITLE
Support Compact Serialization, "zip": "DEF"

### ISSUE THREAD

**Issue by NickDrouin** [jsonwebtoken/jsonwebtoken.github.io#560]
When the header contains "zip": "DEF", apply the DEFLATE algo per [RFC1951](https://www.ietf.org/rfc/rfc1951.txt) after the base64 decode, and prior to further processing of the payload.

Motivation:  The [SMART Health Card Framework](https://spec.smarthealth.cards/#health-cards-are-small) is emerging as a standard for vaccination information.  It uses compact serialization with raw DEFLATE as the JWS payload.  Supporting DEFLATE on jwt.io would allow developers to validate their claims while using the token as emitted by their solutions.

**Comment by panva** [comment]
"zip" JOSE Header Paramater is only registered for use with `JWE`, not `JWS`.
