### ISSUE TITLE
Add RSA support for Signature

### ISSUE THREAD

**Issue by cristiandouce** [jsonwebtoken/jsonwebtoken.github.io#57]
### Expected Flow

1. User should be able to __pick/select__ from a list of supported signature types, as a dropdown or tabs at the debugger: http://jwt.io/#debugger

  ![image](https://cloud.githubusercontent.com/assets/367429/7015909/d3deb4ec-dcb1-11e4-92e9-fee6e546dd82.png)

  > __Note__: UI/UX implementation may vary, the main concern is the implementation.

2. Depending on the algorithm selected for the signature, the user should dispose of an `input[type="text"]` or an `input[type="file"]` at the signature edit section.

  ![image](https://cloud.githubusercontent.com/assets/367429/7015922/35da0228-dcb2-11e4-8d2e-f1c410bced7d.png)

  > __Note__: Secret keys should never be uploaded.

**Comment by pose** [comment]
This has been done.
