### ISSUE TITLE
Debugger support for unsecured JWTs

### ISSUE THREAD

**Issue by JustinIven** [jsonwebtoken/jsonwebtoken.github.io#577]
Support for "none" in the JOSE header according to [RFC 7519 section 6](https://datatracker.ietf.org/doc/html/rfc7519#section-6)

**Comment by DanOnCall** [comment]
Justin, I am one of the newly appointed maintainers for jwt.io and I am working on a new version. I think this is a solid feature request and I am adding it to the roadmap for the next version 💪 cc @byron-okta

**Comment by jonathanp-okta** [comment]
The new Next.js version of jwt.io fully implements unsecured JWT support (alg: none per RFC 7519 Section 6). It is supported in both the encoder and decoder, includes proper validation, and even surfaces a warning message referencing Section 6 when a none algorithm JWT is created.
