### ISSUE TITLE
"Invalid signature" message appears at the bottom of the screen, which can make it hard to see

### ISSUE THREAD

**Issue by jordanrobinson** [jsonwebtoken/jsonwebtoken.github.io#580]
Hello,

I was recently debugging a token issue using the (excellent) https://jwt.io/ - however, it took significantly longer than it probably should have as I didn't notice that there was an "Invalid signature" warning that had appeared at the bottom of the page near the share link.

![image](https://user-images.githubusercontent.com/1202911/152947076-e52cbeb0-fa09-4fb4-a5ec-34e2dab3918a.png)

It's only a small thing but I really think the usability of the site would be improved in these instances if it were above the token window, or if there were some additional feedback to highlight the fact that the signature is invalid.

Thanks,
Jordan

**Comment by Sambego** [comment]
Hey @jordanrobinson thanks for this feedback!

We're working on a visual overhaul of jwt.io and will take this into account :)
