### ISSUE TITLE
Running grunt build-website doesn't fully build the website

### ISSUE THREAD

**Issue by bertrandom** [jsonwebtoken/jsonwebtoken.github.io#599]
When I run
```
grunt build-website
```

It builds the website.. except not the index.html - I need to run
```
grunt pug:website
```

to create that. Shouldn't that be incorporated in the main `build-website` task?

**Comment by MicahParks** [comment]
Running `grunt pug:website` or simply `grunt pug` generates the `index.html` files. Thanks for that hint. However, running `grunt` or `./node_modules/.bin/grunt` actually removes `index.html` and other files, then starts web server.

I've resorted to running `grunt pug`, then using a simple file server in the `dist` directory.

Disclaimer: I'm mostly a backend developer, so I'm not as familiar with frontend frameworks.
