### ISSUE TITLE
Add Scala libraries

### ISSUE THREAD

**Issue by kanerogers** [jsonwebtoken/jsonwebtoken.github.io#6]
Hi there,

The only reasonable implementation of JWT I've seen in Scala is: https://github.com/jasongoodwin/authentikat-jwt

I'd be happy to do the PR to change the HTML, but I have no idea what spec it verifies against, etc.

Do you guys want to check it out and make it passes the spec?

**Comment by pose** [comment]
@kanerogers thanks!

**Comment by kanerogers** [comment]
Ain't no thang. 

---
Kane RogersProduct Manager

CleanStream




t: +61 401 633 346

e: kane@cleanstream.com.au
