### ISSUE TITLE
after click the Decode Header Box at main Page, part of the text auto delete 

### ISSUE THREAD

**Issue by shawnlwy85** [jsonwebtoken/jsonwebtoken.github.io#612]
after click the Decode Header Box at main Page, part of the text auto delete

Steps to trigger
1. goto https://jwt.io/
2. click on the  Decode Header Box

![001](https://user-images.githubusercontent.com/49618844/180210202-2cb174eb-3867-4139-a0b9-882d2acf52c4.png)
![002](https://user-images.githubusercontent.com/49618844/180210210-52cb93b1-db54-4be5-9237-2235d26ac36f.png)
![003](https://user-images.githubusercontent.com/49618844/180210213-85ee94de-6fd3-4969-a108-602d5b683caf.png)

**Comment by shawnlwy85** [comment]
remark.

need to click last line to trigger the bug

![image](https://user-images.githubusercontent.com/49618844/180290355-bb135b9a-1621-4847-bff2-f43369ee3950.png)

**Comment by johanadivare** [comment]
@shawnlwy85 i have the same thing, but if you select and drag to top you can see the text isn't gone its just hidden

**Comment by DanOnCall** [comment]
Hello, all! I am one of the newly appointed maintainers for jwt.io working on a new version of the site. I also detected this bug and it's getting fixed in the next version. I apologize for the delay on this fix 🙏
