### ISSUE TITLE
Ability to provide a complete initial state via URL?  

### ISSUE THREAD

**Issue by jmandel** [jsonwebtoken/jsonwebtoken.github.io#62]
Would you accept a PR allowing all default state values to be passed in via the URL hash?

This would be win for projects that want to refer to jwt.io in their  documentation/examples. See, for example, how we point to jwt.io from the example at the bottom of http://docs.smarthealthit.org/authorization/backend-services/ -- it would be nice to provide a complete working link instead of asking the user to paste in sample values for claims, public key, and private key.

For a site with a similar mechanism, see [this feel link to the json-ld playground](http://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22Jane%20Doe%22%2C%22jobTitle%22%3A%22Professor%22%2C%22telephone%22%3A%22(425)%20123-4567%22%2C%22url%22%3A%22http%3A%2F%2Fwww.janedoe.com%22%7D)

**Comment by rolodato** [comment]
Actually this is already possible, for example: http://jwt.io/?value=foo
