### ISSUE TITLE
Number content omitts zero decimal places

### ISSUE THREAD

**Issue by daniloesk** [jsonwebtoken/jsonwebtoken.github.io#679]
Hi. First of all, thanks for jwt.io website. It is a really convenient way to check JWTs. 👍

We noticed that when payload numbers on decoded they are displayed omitting zero padding decimal places.

Example:
`btoa(String.fromCodePoint(...new TextEncoder().encode('{"width":3.0}')))`
evaluates to
`eyJ3aWR0aCI6My4wfQ==`
and when using it as payload (omitting padding) the site displays as
`
{
  "width": 3
}
`

Converting the Base64 back to string with `atob('eyJ3aWR0aCI6My4wfQ==')` evaluates to exactly the source string.

We understand they are both numbers according to JavaScript, but this brought us some difficulties when matching values.

If this the expected behavior, shouldn't there be a warning about it?

**Comment by panva** [comment]
This is simply how [JSON.parse](https://tc39.es/ecma262/multipage/structured-data.html#sec-json.parse) functions given that `3.0 === 3 // true`, jwt.io employs JSON.parse to display the JWT Claims Set. Standard based `JSON.stringify(3.0)` also gives you "3", not "3.0", so with a JSON serializer you wouldn't end up with your payload.
