### ISSUE TITLE
Bug: Incorrect Date Representation in JavaScript

### ISSUE THREAD

**Issue by ashmit-coder** [jsonwebtoken/jsonwebtoken.github.io#689]
An example token issued by jsonwebtoken is

      const token = jwt.sign({ user: email }, (process.env.SECRET_KEY as string), { expiresIn:(60 * 60)})

The token turns out to be

    { user: '1@1.com', iat: 1712550920, exp: 1712554520 }
    
But JavaScript considers this exp time to be

    Wed Jan 21 1970 01:12:34 GMT+0530 (India Standard Time)
    
**Prescribed Solution:-**
Issue Jwt tokens with the milisecond format

**Comment by panva** [comment]
The token content is correct. These claims' type is `NumericDate` which is as per RFC 7519

A JSON numeric value representing the **number of seconds** from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [[POSIX.1](https://www.rfc-editor.org/rfc/rfc7519.html#ref-POSIX.1)] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339)
      [[RFC3339](https://www.rfc-editor.org/rfc/rfc3339)] for details regarding date/times in general and UTC in
      particular.
