### ISSUE TITLE
Website 2.0

### ISSUE THREAD

**Issue by rickyrauch** [jsonwebtoken/jsonwebtoken.github.io#78]
- [ ] Header mobile
- [ ] Favicons
- [ ] cancel animation when debugging
- [x] Text effect header
- [x] Focus jump
- [ ] Fix heroku's issues https://jwt-io.herokuapp.com/
- [ ] Alert message
- [ ] Mainteiner & Stars count https://cloudup.com/c8d6NbCPKX3
- [x] Add title Store https://cloudup.com/cHn5EzKPiOP
- [ ] On click select all the text https://cloudup.com/cn84u0wdHMD
- [ ] Update logos jwt
- [ ] Add banner auth0 the same call to action CREATE FREE ACCOUNT
- [x] Float right https://cloudup.com/cXOi2VfiHEc

**Comment by pose** [comment]
@rickyrauch is this ready?

**Comment by pose** [comment]
@rickyrauch feel free to re open if it's not done!
