### ISSUE TITLE
Ruby library with extra features

### ISSUE THREAD

**Issue by Foxandxss** [jsonwebtoken/jsonwebtoken.github.io#8]
Hello,

We developed a new gem for [ruby](https://github.com/chupipandi/jwt-rb), we support `exp`, `iss` and `aud`.

Not sure what's the approach you're taking on the web, but you could show both ruby implementations.

**Comment by pose** [comment]
@Foxandxss Sure, could you create a PR with that change so I can merge it? Thanks!

**Comment by sebadoom** [comment]
Closing old report. If there is a library that needs to be added, create a new issue or a new PR. Thanks.
