### ISSUE TITLE
Start tracking encryption and JWK support

### ISSUE THREAD

**Issue by dvsekhvalnov** [jsonwebtoken/jsonwebtoken.github.io#94]
Hi guys,

just as an idea may be it's time to start tracking not only signing, but also encryption and JWK support?

Many libraries looks absolutely same in your list (e.g. almost all support full suite for signing). But if you dig to extended capabilities it will make difference.

Probably it even make sense to split support to: JWT (iss, nbf and other semantic claims), JOSE (sig and encryption) and JWK.

**Comment by bencmbrook** [comment]
This would be a great way of pushing adoption for JWK. The PKI is still really lacking for JWT - even the [Auth0 module requires](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback) public keys be read as `.pem` files.
